server:
  port: 8765
  
zuul:
  prefix: /api
  routes:
    storybox-service:
      path: /storybox-service/**
      url: http://localhost:10000/
    oauth:
      path: /oauth/**
      url: http://localhost:1000/auth-server/oauth
    
  sensitiveHeaders: Cookie,Set-Cookie
    
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:1000/auth-server/oauth/user
    client:
      client-id: storybox
      client-secret: storybox-super-secure